
# ワークフロー名
name: mail_bot

on:
  schedule:
    # 毎時0分に実行（例：1時間おき）
    - cron: '* * * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
          pip install requests

          
      - name: Run script
        env:
          IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
          EMAIL_ACCOUNT: ${{ secrets.EMAIL_ACCOUNT }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # 定期実行するファイルを指定。・・・③
          python3 mail_auto.py
